"""fix UserQuizSession col score, streak

Revision ID: 173e5096902d
Revises: c6d24a26e7fb
Create Date: 2025-01-10 22:04:27.384622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173e5096902d'
down_revision: Union[str, None] = 'c6d24a26e7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quiz_sessions', sa.Column('current_streak', sa.Integer(), nullable=False))
    op.add_column('user_quiz_sessions', sa.Column('max_streak', sa.Integer(), nullable=False))
    op.add_column('user_quiz_sessions', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('user_quiz_sessions', sa.Column('total_questions', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_quiz_sessions_id'), 'user_quiz_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_attempts_id'), 'user_attempts',['id'],unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quiz_sessions_id'), table_name='user_quiz_sessions')
    op.drop_index(op.f('ix_user_attempts_id'), table_name='user_attempts')
    op.drop_column('user_quiz_sessions', 'total_questions')
    op.drop_column('user_quiz_sessions', 'score')
    op.drop_column('user_quiz_sessions', 'max_streak')
    op.drop_column('user_quiz_sessions', 'current_streak')
    # ### end Alembic commands ###
