"""fix: UserAttempts

Revision ID: 43b1d0cc78b9
Revises: 173e5096902d
Create Date: 2025-01-11 08:18:38.492560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b1d0cc78b9'
down_revision: Union[str, None] = '173e5096902d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attempts', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attempts', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
