"""fixed Quiz and Question localizations

Revision ID: c6d24a26e7fb
Revises: d93e84cb4677
Create Date: 2025-01-06 19:00:48.280293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6d24a26e7fb'
down_revision: Union[str, None] = 'd93e84cb4677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'content')
    op.drop_column('quizzes', 'description')
    op.drop_column('quizzes', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
