services:

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - quiz-net

  quiz_service:
    build: ./quiz_service
    ports:
      - "9000:9000"
    volumes:
      - ./quiz_service/:/app
    environment:
      - DB_USER=quiz_user
      - DB_PASSWORD=quiz_password
      - DB_HOST=quiz_db
      - DB_PORT=5432
      - DB_NAME=quiz_db
      - DEBUG=True
    networks:
      - quiz-net
    depends_on:
      - quiz_db
      - rabbitmq


  balance_service:
    build: ./balance_service
    ports:
      - "9001:9001"
    volumes:
      - ./balance_service/:/app
    environment:
      - DB_USER=balance_user
      - DB_PASSWORD=balance_password
      - DB_HOST=balance_db
      - DB_PORT=5432
      - DB_NAME=balance_db
      - DEBUG=True
    networks:
      - quiz-net
    depends_on:
      - rabbitmq
      - balance_db

  quiz_db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
      POSTGRES_DB: quiz_db
    ports:
      - "5435:5432"
    networks:
      - quiz-net
    volumes:
        - postgres_data:/var/lib/postgresql/data


  balance_db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: balance_user
      POSTGRES_PASSWORD: balance_password
      POSTGRES_DB: balance_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_balance:/var/lib/postgresql/data
    networks:
      - quiz-net

  krakend:
    image: devopsfaith/krakend:2.1
    ports:
      - "9999:8080"
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
    networks:
      - quiz-net
    depends_on:
      - quiz_service
      - balance_service



volumes:
  postgres_data:
  postgres_data_balance:
networks:
  quiz-net:
    driver: bridge
